routes/index.py
import os
import time
import uuid

from flask import (
    abort,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    current_app,
    make_response,
    render_template,
    send_from_directory,
)
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from models.message import Messages
from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import current_user, cache, login_required

import json

from utils import log


main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


# class TopicEncoder(json.JSONEncoder ):
#     def default(self, obj):
#         if isinstance(obj, Topic):
#             return obj.__str__()
#         return json.JSONEncoder.default(self, obj)


def topichook(dic):
    print("cache.ts", dic)
    if dic['id']:
        return Topic.one(id=dic['id'])
    return dic


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # 将session 存写入 redis
        session_id = str(uuid.uuid4())
        key = 'session_id_{}'.format(session_id)
        cache.set(key, u.id)
        # 设置header中set-cookie字段 并指定跳转路由
        redirect_to_index = redirect(url_for('topic.index'))
        response = current_app.make_response(redirect_to_index)
        response.set_cookie('session_id', value=session_id)
        # 转到 topic.index 页面
        return response


def created_topic(user_id):
    # O(n)
    ts = Topic.query.filter_by(user_id=user_id)\
                    .order_by(Topic.created_time.desc())\
                    .all()
    # ts = Topic.all(user_id=user_id)
    return ts
    #
    # k = 'created_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     ts = Topic.all(user_id=user_id)
    #     ts = sorted(ts, key=lambda x: x.created_time, reverse=True)
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #     return ts


def replied_topic(user_id):
    # 避免ORM的n+1问题
    k = 'replied_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        ts = json.loads(v, object_hook=topichook)
        return ts
    else:
        # 调用SQLAlchemy join拼接table；filter查询；order_by排序；desc()倒序
        # 解决ORM的n+1问题
        ts = Topic.query.join(Reply, Reply.topic_id == Topic.id)\
                        .filter(Reply.user_id == user_id)\
                        .order_by(Reply.created_time.desc())\
                        .all()
        # rs = Reply.all(user_id=user_id)
        # ts = []
        # for r in rs:
        #     t = Topic.one(id=r.topic_id)
        #     ts.append(t)
        # ts = sorted(ts, key=lambda x: x.updated_time, reverse=True)
        v = json.dumps([t.json() for t in ts])
        cache.set(k, v)
        return ts


@main.route('/profile')
@login_required
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/setting')
@login_required
def setting():
    u = current_user()
    return render_template('setting.html', user=u)


@main.route('/change', methods=['POST'])
def change():
    u = current_user()
    form = request.form.to_dict()
    print('change', form)
    form['updated_time'] = int(time.time())
    User.update(u.id, **form)
    return redirect(url_for('.setting'))


@main.route('/change_pass', methods=['POST'])
def change_pass():
    u = current_user()
    form = request.form.to_dict()
    if u.password == User.salted_password(form['old_pass']):
        u.password = User.salted_password(form['password'])
        form['password'] = u.password
        form['updated_time'] = int(time.time())
        form.pop('old_pass')
        User.update(u.id, **form)
    return redirect(url_for('.setting'))


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # 不能直接存用戶使用的文件名
    # 有可能被讀取到server文件
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # 可以使用flask的安全文件名函數進行保護
    # filename = secure_filename(file.filename)
    # 文件名后綴也可以被省略
    # suffix = file.filename.split('.')[-1]
    # filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    filename = str(uuid.uuid4())
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.profile'))


@main.route('/images/<filename>')
def image(filename):
    # 不能直接拼接路由，不安全，比如
    # http://localhost:2000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)


@main.route("/reset/send", methods=["POST"])
def send():
    form = request.form.to_dict()
    username = form['username']
    u = User.one(username=username)
    if u is not None:
        token = str(uuid.uuid4())
        cache.set(token, u.id)
        cache.expire(token, 1800)
        title = '来自 {} 的密码找回信件'.format(u.username)
        content = 'http://www.corgist.xyz/reset/view?token={}'.format(token)
        Messages.send(
            title=title,
            content=content,
            sender_id=1,
            receiver_id=u.id
        )
    else:
        abort(404)
    return redirect(url_for('.index'))


@main.route("/reset/view")
def view():
    token = request.args.get('token')
    if cache.exists(token):
        return render_template('seek_secret.html', token=token)
    else:
        abort(404)


@main.route("/reset/update", methods=['POST'])
def update():
    form = request.form.to_dict()
    password = form['password']
    token = form['token']
    if cache.exists(token):
        u = User.one(id=int(cache.get(token)))
        form['password'] = User.salted_password(password)
        form['updated_time'] = int(time.time())
        form.pop('token')
        User.update(u.id, **form)
    return redirect(url_for('.index'))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board
from models.reply import Reply

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    u = current_user()
    if u is None:
        return redirect("../")
    else:
        board_id = int(request.args.get('board_id', -1))
        if board_id == -1:
            ms = Topic.all()
        else:
            ms = Topic.all(board_id=board_id)
        token = new_csrf_token()
        bs = Board.all()
        return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=u)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/delete")
@csrf_required
@login_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    r = Reply.all(topic_id=id)
    for i in r:
        i.delete(i.id)
    # 删除redis中该贴发帖人的缓存，与数据库同步
    k = 'replied_topic_{}'.format(u.id)
    if cache.exists(k):
        cache.delete(k)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/index.html
{% extends "topic/base.html" %}
{% block title %}bbs club{% endblock%}
{% block main %}

<div id="main">
  <div id="sidebar">
    <div class="panel">
        <div class="header">
          <span class="col_fade">个人信息</span>
        </div>
        <div class="inner">
          <div class="user_card">
            <div>
                <a class="user_avatar" href="{{ url_for('.profile') }}">
                  <img src="{{ user.image }}" title="{{ user.username }}">
                </a>
                <span class="user_name">
                    <a class="dark" href="{{ url_for('.profile') }}">
                        {{ user.username }}
                    </a>
                </span>
                <div class="space clearfix"></div>
                <span class="signature">
                    {{ user.signature }}
                </span>
            </div>
          </div>
        </div>
    </div>
  </div>

  <div id="content">
    <div class="panel">
        <div class="header">
          <span class="col_fade">注册</span>
        </div>
        <div class="inner">
          <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
            <div class="control-group">
                <label class="control-label">用户名</label>
                <div class="controls">
                    <input type="text" placeholder="用户名至少为 3 位" class="input-xlarge" name="username">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">密码</label>
                <div class="controls">
                    <input type="text" placeholder="密码至少为 3 位" class="input-xlarge" name="password">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">邮箱</label>
                <div class="controls">
                    <input type="text" class="input-xlarge" name="email">
                </div>
            </div>
            <div class="form-actions">
                <input type="submit" class="span-primary" value="注册">
            </div>
          </form>
        </div>
    </div>

    <div class="panel">
        <div class="header">
          <span class="col_fade">登录</span>
        </div>
        <div class="inner">
          <form class="form-horizontal" method="post" action="{{ url_for('.login') }}">
            <div class="control-group">
                <label class="control-label">用户名</label>
                <div class="controls">
                    <input type="text" class="input-xlarge" name="username">  测试账号：test
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">密码</label>
                <div class="controls">
                    <input type="text" class="input-xlarge" name="password">  测试密码：123
                </div>
            </div>
            <div class="form-actions">
                <input type="submit" class="span-primary" value="登录">
            </div>
          </form>
        </div>
    </div>

    <div class="panel">
        <div class="header">
          <span class="col_fade">密码重置</span>
        </div>
        <div class="inner">
          <form class="form-horizontal" method="post" action="{{ url_for('.send') }}">
            <div class="control-group">
                <label class="control-label">用户名</label>
                <div class="controls">
                    <input type="text" class="input-xlarge" name="username">
                </div>
            </div>
            <div class="form-actions">
                <input type="submit" class="span-primary" value="密码重置" onclick="remind()">
            </div>
          </form>
        </div>
    </div>
  </div>
</div>

<script>
  function remind() {
    alert('邮件已发送')
  };
</script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/profile.html
{% extends "topic/base.html" %}
{% block title %}个人主页{% endblock%}
{% block main %}

<div id="main">
  <div id="sidebar">
    <div class="panel">
      <div class="header">
        <span class="col_fade">个人信息</span>
      </div>
      <div class="inner">
        <div class="user_card">
          <div>
            <a class="user_avatar" href="{{ url_for('index.user_detail', id=user.id) }}">
            <img src="{{ user.image }}" title="{{ user.username }}">
            </a>
            <span class="user_name">
                <a class="dark" href="{{ url_for('index.user_detail', id=user.id) }}">
                    {{ user.username }}
                </a>
            </span>
            <div class="board clearfix"></div>
            <div class="space clearfix"></div>
            <span class="signature">
                {{ user.signature }}
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="content">
      <div class="panel">
        <div class="header">
          <ul class="breadcrumb">
            <li>主页</a><span class="divider">/</span></li>
          </ul>
        </div>
        <div class="inner userinfo">
          <div class="user_big_avatar" >
            <img src="{{ user.image }}" class="user_avatar" title="{{ user.username }}">
          </div>
          <a class="dark" title="{{ user.username }}"></a>

          <div class="user_profile">
            <ul class="unstyled">
              <li>
                <a class="dark" href="{{ url_for('index.user_detail', id=user.id) }}" target="_blank">
                  @{{ user.username }}
                </a>
              </li>
            </ul>
          </div>
          <p class="col_fade">注册时间 {{ user.created_time | history_time }}前</p>

        </div>
      </div>

      <div class="panel">
        <div class="header">
          <span class="col_fade">最近创建的话题</span>
        </div>
        {% for t in created %}
        {% set re = t.replies() %}
          <div class="cell">
            <a class="user_avatar pull-left" href="{{ url_for('index.user_detail', id=user.id) }}">
            <img src="{{ user.image }}" title="{{ user.username }}"/>
                {{ user.username }}
            </a>

            <span class="reply_count pull-left">
                <span class="count_of_replies" title="回复数">
                  {{ t.reply_count() }}
                </span>
                <span class="count_seperator">/</span>
                <span class="count_of_visits" title='点击数'>
                  {{ t.views }}
                </span>
            </span>
            {% if re == [] %}
                <span class='last_time pull-right'>
                    <span class="last_active_time">{{ t.created_time | history_time }} 前</span>
                </span>
            {% else %}
                <a class='last_time pull-right' href="{{ url_for('index.user_detail', id=re[-1].user().id) }}">
                    <img class="user_small_avatar" src="{{ re[-1].user().image }}">
                    <span class="last_active_time">{{ re[-1].created_time | history_time }} 前</span>
                </a>
            {% endif %}
            <div class="topic_title_wrapper">
              <a class='topic_title' href="{{ url_for('topic.detail', id=t.id) }}" title="{{ t.title }}">
                  {{ t.title }}
              </a>
            </div>
          </div>
        {% endfor %}
      </div>

      <div class="panel">
        <div class="header">
          <span class="col_fade">最近参与的话题</span>
        </div>
        {% for r in replied %}
          {% set u = r.user() %}
          {% set re = r.replies() %}
          <div class="cell">
            <a class="user_avatar pull-left" href="{{ url_for('index.user_detail', id=u.id) }}">
            <img src="{{ u.image }}" title="{{ u.username }}"/>
                {{ u.username }}
            </a>

            <span class="reply_count pull-left">
                <span class="count_of_replies" title="回复数">
                  {{ r.reply_count() }}
                </span>
                <span class="count_seperator">/</span>
                <span class="count_of_visits" title='点击数'>
                  {{ r.views }}
                </span>
            </span>

            <a class='last_time pull-right' href="{{ url_for('index.user_detail', id=re[-1].user().id) }}">
                <img class="user_small_avatar" src="{{ re[-1].user().image }}">
                <span class="last_active_time">{{ re[-1].created_time | history_time }} 前</span>
            </a>

            <div class="topic_title_wrapper">
              <a class='topic_title' href="{{ url_for('topic.detail', id=r.id) }}" title="{{ r.title }}">
                  {{ r.title }}
              </a>
            </div>
          </div>
        {% endfor %}
      </div>
  </div>
</div>


{% endblock %}

templates/seek_secret.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>密码找回</title>
</head>
<body>
    <form class="form-horizontal" method="post" action="{{ url_for('.update')}}">
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
                <input type="hidden" class="input-xlarge" name="token" value="{{ token }}">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="确定">
        </div>
    </form>
</body>
</html>

templates/setting.html
{% extends "topic/base.html" %}
{% block title %}设置{% endblock%}
{% block main %}

<div id="main">
  <div id="sidebar">
    <div class="panel">
        <div class="header">
          <span class="col_fade">个人信息</span>
        </div>
        <div class="inner">
          <div class="user_card">
            <div>
                <a class="user_avatar" href="{{ url_for('.profile') }}">
                  <img src="{{ user.image }}" title="{{ user.username }}">
                </a>
                <span class="user_name">
                    <a class="dark" href="{{ url_for('.profile') }}">
                        {{ user.username }}
                    </a>
                </span>
                <div class="space clearfix"></div>
                <span class="signature">
                    {{ user.signature }}
                </span>
            </div>
          </div>
        </div>
    </div>

    <div class="panel">
        <div class="inner">
          <a href="/topic/new?board_id=-1" id="create_topic_btn">
            <span class="span-success">发布话题</span>
          </a>
        </div>
    </div>
  </div>

  <div id="content">
    <div class="panel">
        <div class="header">
          <ul class="breadcrumb">
            <li><a href="{{ url_for('index.profile') }}">主页</a><span class="divider">/</span></li>
            <li class="active">设置</li>
          </ul>
        </div>
        <div class="inner">
          <form id="setting_form" class="form-horizontal" action="{{ url_for('.change') }}" method="post">
            <div class="control-group">
              <label class="control-label" for="name">用户名</label>

              <div class="controls">
                <input class="input-xlarge" id="name" name="username" size="30" type="text" value="{{ user.username }}">
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="signature">个性签名</label>

              <div class="controls">
                <input class="input-xlarge" id="signature" name="signature" size="30" type="text" value="{{ user.signature }}">
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="signature">邮箱</label>

              <div class="controls">
                <input class="input-xlarge" id="email" name="email" size="30" type="text" value="{{ user.email }}">
              </div>
            </div>
            <input type="hidden" id="action" name="action" value="change_setting">
            <input type="hidden" name="_csrf" value="ponoP4Xc-UNEN_zT6A01cqh3VKGRwTDkWaGw">

            <div class="form-actions">
              <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
            </div>
          </form>
        </div>
    </div>

    <div class="panel">
        <div class="header">
          <span class="col_fade">更改密码</span>
        </div>
        <div class="inner">
          <form id="change_pass_form" class="form-horizontal" action="{{ url_for('.change_pass') }}" method="post">
            <div class="control-group">
              <label class="control-label" for="old_pass">当前密码</label>

              <div class="controls">
                <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="password">新密码</label>

              <div class="controls">
                <input class="input-xlarge" type="password" id="password" name="password" size="30">
              </div>
            </div>

            <div class="form-actions">
              <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
            </div>
          </form>
    </div>
    </div>

    <div class="panel">
        <div class="header">
          <span class="col_fade">上传头像</span>
        </div>
        <div class="inner">
            <form method="post"
                action="{{ url_for('.avatar_add')}}"
                enctype="multipart/form-data"
            >
                <input type="file" name="avatar">
                <button type="submit">上传头像</button>
            </form>
        </div>
    </div>
  </div>

</div>

{% endblock %}