models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)

    @classmethod
    def new(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

routes/index.py
import os
import time
import uuid

from flask import (
    abort,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    current_app,
    make_response,
    render_template,
    send_from_directory,
)
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from models.message import Messages
from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import current_user, cache, login_required

import json

from utils import log


main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


# class TopicEncoder(json.JSONEncoder ):
#     def default(self, obj):
#         if isinstance(obj, Topic):
#             return obj.__str__()
#         return json.JSONEncoder.default(self, obj)


def topichook(dic):
    print("cache.ts", dic)
    if dic['id']:
        return Topic.one(id=dic['id'])
    return dic


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # 将session 存写入 redis
        session_id = str(uuid.uuid4())
        key = 'session_id_{}'.format(session_id)
        cache.set(key, u.id)
        # 设置header中set-cookie字段 并指定跳转路由
        redirect_to_index = redirect(url_for('topic.index'))
        response = current_app.make_response(redirect_to_index)
        response.set_cookie('session_id', value=session_id)
        # 转到 topic.index 页面
        return response


def created_topic(user_id):
    # O(n)
    ts = Topic.query.filter_by(user_id=user_id)\
                    .order_by(Topic.created_time.desc())\
                    .all()
    # ts = Topic.all(user_id=user_id)
    return ts
    #
    # k = 'created_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     ts = Topic.all(user_id=user_id)
    #     ts = sorted(ts, key=lambda x: x.created_time, reverse=True)
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #     return ts


def replied_topic(user_id):
    # 避免ORM的n+1问题
    k = 'replied_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        ts = json.loads(v, object_hook=topichook)
        return ts
    else:
        # 调用SQLAlchemy join拼接table；filter查询；order_by排序；desc()倒序
        # 解决ORM的n+1问题
        ts = Topic.query.join(Reply, Reply.topic_id == Topic.id)\
                        .filter(Reply.user_id == user_id)\
                        .order_by(Reply.created_time.desc())\
                        .all()
        # rs = Reply.all(user_id=user_id)
        # ts = []
        # for r in rs:
        #     t = Topic.one(id=r.topic_id)
        #     ts.append(t)
        # ts = sorted(ts, key=lambda x: x.updated_time, reverse=True)
        v = json.dumps([t.json() for t in ts])
        cache.set(k, v)
        return ts


@main.route('/profile')
@login_required
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/setting')
@login_required
def setting():
    u = current_user()
    return render_template('setting.html', user=u)


@main.route('/change', methods=['POST'])
def change():
    u = current_user()
    form = request.form.to_dict()
    print('change', form)
    form['updated_time'] = int(time.time())
    User.update(u.id, **form)
    return redirect(url_for('.setting'))


@main.route('/change_pass', methods=['POST'])
def change_pass():
    u = current_user()
    form = request.form.to_dict()
    if u.password == User.salted_password(form['old_pass']):
        u.password = User.salted_password(form['password'])
        form['password'] = u.password
        form['updated_time'] = int(time.time())
        form.pop('old_pass')
        User.update(u.id, **form)
    return redirect(url_for('.setting'))


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # 不能直接存用戶使用的文件名
    # 有可能被讀取到server文件
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # 可以使用flask的安全文件名函數進行保護
    # filename = secure_filename(file.filename)
    # 文件名后綴也可以被省略
    # suffix = file.filename.split('.')[-1]
    # filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    filename = str(uuid.uuid4())
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.profile'))


@main.route('/images/<filename>')
def image(filename):
    # 不能直接拼接路由，不安全，比如
    # http://localhost:2000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)


@main.route("/reset/send", methods=["POST"])
def send():
    form = request.form.to_dict()
    username = form['username']
    u = User.one(username=username)
    if u is not None:
        token = str(uuid.uuid4())
        cache.set(token, u.id)
        cache.expire(token, 1800)
        title = '来自 {} 的密码找回信件'.format(u.username)
        content = 'http://www.corgist.xyz/reset/view?token={}'.format(token)
        Messages.send(
            title=title,
            content=content,
            sender_id=1,
            receiver_id=u.id
        )
    else:
        abort(404)
    return redirect(url_for('.index'))


@main.route("/reset/view")
def view():
    token = request.args.get('token')
    if cache.exists(token):
        return render_template('seek_secret.html', token=token)
    else:
        abort(404)


@main.route("/reset/update", methods=['POST'])
def update():
    form = request.form.to_dict()
    password = form['password']
    token = form['token']
    if cache.exists(token):
        u = User.one(id=int(cache.get(token)))
        form['password'] = User.salted_password(password)
        form['updated_time'] = int(time.time())
        form.pop('token')
        User.update(u.id, **form)
    return redirect(url_for('.index'))

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    Request)

from models.message import Messages
from models.topic import Topic
from routes import *

from models.reply import Reply
from routes.index import topichook

main = Blueprint('reply', __name__)


def users_from_content(content):
    # 内容 @123 内容
    # 如果用户名含有空格 就不行了 @name 123
    # 'a b c' -> ['a', 'b', 'c']
    parts = content.split()
    users = []

    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.one(username=username)
            print('users_from_content <{}> <{}> <{}>'.format(username, p, parts))
            if u is not None:
                users.append(u)

    return users


def send_mails(sender, receivers, reply_link, reply_content):
    print('send_mail', sender, receivers, reply_content)
    content = '链接：{}\n内容：{}'.format(
        reply_link,
        reply_content
    )
    for r in receivers:
        title = '你被 {} AT 了'.format(sender.username)
        Messages.send(
            title=title,
            content=content,
            sender_id=sender.id,
            receiver_id=r.id
        )


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    # 在回复中判断@对象 并发送私信
    content = form['content']
    users = users_from_content(content)
    send_mails(u, users, request.referrer, content)
    # 添加回复，并更新topic的updated_time
    form = form.to_dict()
    m = Reply.new(form, user_id=u.id)
    Topic.update(m.topic_id, updated_time=m.updated_time)
    # 更新redis内的replied_topic
    k = 'replied_topic_{}'.format(u.id)
    if cache.exists(k):
        cache.delete(k)
    # rs = Reply.all(user_id=u.id)
    # ts = []
    # for r in rs:
    #     t = Topic.one(id=r.topic_id)
    #     ts.append(t)
    # v = json.dumps([t.json() for t in ts])
    # cache.set(k, v)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board
from models.reply import Reply

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    u = current_user()
    if u is None:
        return redirect("../")
    else:
        board_id = int(request.args.get('board_id', -1))
        if board_id == -1:
            ms = Topic.all()
        else:
            ms = Topic.all(board_id=board_id)
        token = new_csrf_token()
        bs = Board.all()
        return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=u)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/delete")
@csrf_required
@login_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    r = Reply.all(topic_id=id)
    for i in r:
        i.delete(i.id)
    # 删除redis中该贴发帖人的缓存，与数据库同步
    k = 'replied_topic_{}'.format(u.id)
    if cache.exists(k):
        cache.delete(k)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="//cdn.bootcss.com/prism/1.8.0/themes/prism.css" rel="stylesheet">
<head>
<body>

<!-- navbar -->
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <ul class='nav pull-right'>
        <li><a href='/topic'>首页</a></li>

        <li><a href='/profile'>个人主页</a></li>
        <li><a href='/setting'>设置</a></li>
        <li><a href='/mail'>站内信</a></li>
        <li><a href='/'>注册</a></li>
        <li><a href='/'>登录</a></li>
        <li><a href="/">密码找回</a></li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>

{% block main %}
{% endblock %}
<a href="http://www.beian.miit.gov.cn" ><center>ICP备案号：津ICP备19006090号-1</center></a>
</body>

templates/topic/detail.html
{% extends "topic/base.html" %}
{% block title %}{{ topic.title }}{% endblock%}
{% block main %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
            <span class="topic_full_title">
                {{ topic.title }}
            </span>
            <div class="changes">
                <span>
                    发布于 {{ topic.created_time | format_time }}
                </span>
                <span>
                    {% set u = topic.user() %}
                    作者<a href="{{ url_for('index.user_detail', id=u.id) }}">{{ u.username }}</a>
                </span>
                <span>
                    {{ topic.views }} 次浏览
                </span>
{#                <span>#}
{#                    来自 问答#}
{#                </span>#}
            </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content}}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
            {% set u = r.user() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <a class="user_avatar" href="{{ url_for('index.user_detail', id=u.id) }}">
                    <img src="{{ u.image }}" title="{{ u.username }}"/>
                    </a>
                    <div class='user_info'>
                        <a class='dark reply_author' href="{{ url_for('index.user_detail', id=u.id) }}">
                            {{ u.username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼 / {{ loop.length }}楼 •
                            <span>{{ r.created_time | format_time }}</span>
                        </a>
                    </div>
                    <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢">
                        </i>
                        <span class="up-count">
                        </span>
                    </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">{{ r.content }}</div>
{#                    <div class="markdown-text">{{ r.content | safe | remove_script }}</div>#}
                </div>
            </div>
        {% endfor %}
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
    </div>
</div>


<link rel="stylesheet" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/style.css">
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> language 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
         // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var __main = function () {
        markContents()
        highlight()
    }

    __main()

</script>

{% endblock %}

templates/topic/index.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>bbs club</title>-->
    <!--<link rel="stylesheet" href="/static/css/bootstrap.min.css">-->
    <!--<link rel="stylesheet" href="/static/css/style.css">-->
<!--</head>-->
<!--<body>-->
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock%}
{% block main %}

<div id="main">
    <div id="sidebar">
        <div class="panel">
        <div class="header">
          <span class="col_fade">个人信息</span>
        </div>
        <div class="inner">
          <div class="user_card">
            <div>
                <a class="user_avatar" href="{{ url_for('index.profile') }}">
                  <img src="{{ user.image }}" title="{{ user.username }}">
                </a>
                <span class="user_name">
                    <a class="dark" href="{{ url_for('index.profile') }}">
                        {{ user.username }}
                    </a>
                </span>
                <div class="space clearfix"></div>
                <span class="signature">
                    {{ user.signature }}
                </span>
            </div>
          </div>
        </div>
    </div>

        <div class="panel">
            <div class="inner">
                <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>
                            <!--<a class="topic_title" href="{{ url_for('topic.delete', id=t.id) }}">-->
                            <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                删除
                            </a>

                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();

</script>

{% endblock %}


<!--</body>-->
<!--</html>-->

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
<!--<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">-->
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择版块：</span>
        <select name="board_id" id="board" required>
            {% for b in bs %}
                {% if bid == b.id %}
                    <option value="{{ b.id }}" selected >{{ b.title }}</option>
                {% else %}
                    <option value="{{ b.id }}" >{{ b.title }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>